---
title: "Map Predictions"
author: "Michelle Evans"
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(rgdal)
library(viridis)
library(lubridate)
library(raster)
library(stringr)
library(dplyr)
```

This document creates a gif of the predictions from the bagging model.

```{r load data}
predictions <- readRDS("../data_out/Predictions/SFPPredPlot.rds")

brazil <- readOGR("../data_clean", "BRAZpolygons")
#fortify for ggplot2
brazFortified <- fortify(brazil, region = "muni_no") %>% 
  mutate(muni.no = as.numeric(id))

#get brazil outline
brazOutline <- getData('GADM', country ='BRA', level = 0)
outlineFortify <- fortify(brazOutline, region = "OBJECTID") 
```


```{r create map theme}
theme_map <- function(...) {
  theme_minimal() +
  theme(
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    # panel.grid.minor = element_line(color = "#ebebe5", size = 0.2),
    panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "#f5f5f2", color = NA), 
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.border = element_blank(),
    ...
  )
}

```


```{r create plotting function, eval = F}
plotFunction <- function(monthIteration){
  #set title
  mapTitle <- paste("Model predictions for", month(monthIteration %% 12, label = T), (2001 + monthIteration %/% 12), sep = " ")
  
  #subset data
  subset2plot <- as.data.frame(predictions[predictions[,2]==monthIteration,])

  # now we join the thematic data
  map_data <- brazFortified %>% 
  left_join(subset2plot, by = "muni.no")
  
  p <-ggplot() +
    # municipality polygons
    geom_polygon(data = map_data, aes(fill = prediction, 
                                        x = long, 
                                        y = lat, 
                                        group = group)) +
    # add outline of all of brazil
    geom_path(data = outlineFortify, aes(x = long, 
                                   y = lat, 
                                   group = group), 
              color = "gray25", size = 0.1) +
    # add shape for cases
    geom_point(data = map_data[map_data$case==1,], 
               aes(x = long, y = lat), 
               shape = 23, size = 1, col = "green") +
    coord_equal() +
    scale_color_manual(values = caseColor) +
    scale_fill_viridis(option = "magma", direction = -1, discrete = F,
                       na.value = "gray90", 
                       guide = guide_colorbar(
                                direction = "horizontal",
                                barheight = unit(2, units = "mm"),
                                barwidth = unit(50, units = "mm"),
                                draw.ulim = F,
                                title.position = 'top',
                                # some shifting around
                                title.hjust = 0.5,
                                label.hjust = 0.5),
                       limits = c(0,1)) +
    # add the previously defined basic theme
    theme_map() +
    guides(color = F) +
    labs(x = NULL, 
         y = NULL, 
         title = mapTitle, 
         subtitle = "True positive cases are noted by green diamonds.") +
    theme(legend.position = "bottom")
  
  return(p)  
  #dev.off()
}
```

```{r, eval = F}
for (i in 1:168){
  #wrap in try catch because of image device failings
  tryCatch({
  png(paste0("figures/GIFplots/month", str_pad(i, 3, pad = "0"), ".png"), res = 400, 
      width = 5, height = 5, units = "in")
  p <- plotFunction(monthIteration = i)
  print(p)
  dev.off()
  # add a bunch of this becuase my image device is broke :(
  #dev.off()
  #dev.off()
  })
}

```
You will then need to use image Magick to combine into one giant gif.


Try it using `gganimate`. This runs faster, but makes lower quality plots (resolution wise).

Create the plot.
```{r}
preds <- as.data.frame(predictions)

#create month levels so they plot in order
month_levels <- paste(month(1:12, label = T), rep(2001:2014, each =12), sep = " ")

 # now we join the prediction data
  map_data <- brazFortified %>% 
  left_join(preds, by = c("muni.no")) %>%
  filter(!is.na(month.no)) %>%
  arrange(month.no) %>%
  #create title/frame for gganimate
  mutate(mapTitle = factor(paste(month(month.no %% 12, label = T), 
                                 (2001 + month.no %/% 12), sep = " "), 
                           levels = month_levels))
  
  monthOutline <- data.frame(mapTitle = unique(map_data$mapTitle), id = "1")
  #join outline data too
  outlineFortifyAnimate <- outlineFortify %>%
    left_join(monthOutline, by = "id")
  
  p <-ggplot(data = map_data, aes(frame = mapTitle)) +
    # municipality polygons
    geom_polygon(data = map_data, aes(fill = prediction, 
                                      x = long, 
                                      y = lat, 
                                      group = group)) +
    # add outline of all of brazil
    geom_path(data = outlineFortifyAnimate, aes(x = long,
                                   y = lat,
                                   group = group),
              color = "gray25", size = 0.1) +
    # add shape for cases
    geom_point(data = map_data[map_data$case==1,], 
               aes(x = long, y = lat), 
               shape = 23, size = 1, col = "green") +
    coord_equal() +
    scale_color_manual(values = caseColor) +
    scale_fill_viridis(option = "magma", direction = -1, discrete = F,
                       na.value = "gray70", 
                       guide = guide_colorbar(
                                direction = "horizontal",
                                barheight = unit(2, units = "mm"),
                                barwidth = unit(50, units = "mm"),
                                draw.ulim = F,
                                title.position = 'top',
                                # some shifting around
                                title.hjust = 0.5,
                                label.hjust = 0.5),
                       limits = c(0,1)) +
    # add the previously defined basic theme
    theme_map() +
    guides(color = F) +
    labs(x = NULL, 
         y = NULL, 
         #title = mapTitle, 
         subtitle = "True positive cases are noted by green diamonds.") +
    ggtitle("Model predictions for ") +
    theme(legend.position = "bottom")
```

Animate and save.
```{r}
gganimate(p, interval = 1.5, "figures/mapPredictionsAll.gif")
```

