---
title: "Openning the testing data!"
author: "Evans and Kaul"
date: "January 23, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load packages
library(dplyr)
library(gplots)
library(parallel)
library(doParallel)
library(ROCR)
library(pROC)

#source functions
source("functions/baggingWperm.R")

#load the data and trim it

#One Model Data
one.training <- readRDS("../data_clean/TrainingDataSpat.rds")
one.testing <- readRDS("../data_clean/TestingData.rds")

one.trainTrim <- one.training %>% filter(year <2014)
one.testTrim <- one.testing %>% filter(year <2014)

#one.data <- bind_rows(one.trainTrim, one.testTrim)

#Two Model Data 

##high
high.training <- readRDS("../data_clean/TrainingDataHighNHP.rds")
high.testing <- readRDS("../data_clean/TestingDataHighNHP.rds")

high.trainTrim <- high.training %>% filter(year <2014)
high.testTrim <- high.testing %>% filter(year <2014)

high.data <- bind_rows(high.trainTrim, high.testTrim)

##low
low.training <- readRDS("../data_clean/TrainingDataLowNHP.rds")
low.testing <- readRDS("../data_clean/TestingDataLowNHP.rds")

low.trainTrim <- low.training %>% filter(year <2014)
low.testTrim <- low.testing %>% filter(year <2014)

low.data <- bind_rows(low.trainTrim, low.testTrim)

#Model
glm.formula <- as.formula("case~  NDVI+NDVIScale+
                          popLog10+
                          RF+RFsqrt+RFScale+
                          tempMean+tempScale+
                          fireDenSqrt+fireDenScale+
                          spRich+primProp") 
```

# Openning the testing data


## One Model

```{r one model}

#build model and predictions on training data
one.model <-  BaggedModel(form.x.y = glm.formula, training = one.trainTrim, new.data = one.trainTrim, no.iterations = 500, bag.fnc = baggingTryCatch)

list.of.one.models <- one.model[[1]]
#predict on testing data
one.test.pred <- baggedPredictions(list.of.one.models, one.testTrim)

#test auc
one.test.pred[[1]]

#predictions for whole dataset
#add col to tell if in training vs testing 
one.model.prediction <- one.model[[2]] %>%
                          bind_rows(one.test.pred[[2]]) %>%
                          mutate(set=c(rep("train", dim(one.model[[2]])[1]), rep("test", dim(one.test.pred[[2]])[1])))

#save all the things
saveRDS(one.model, file="../data_out/MS_results/OneModel/model.rds")
saveRDS(one.test.pred, file="../data_out/MS_results/OneModel/testingPredictions.rds")
saveRDS(one.model.prediction, file="../data_out/MS_results/OneModel/wholePredictions.rds")

```


## Two Model

```{r two model High}


#build model and predictions on training data
high.model <-  BaggedModel(form.x.y = glm.formula, training = high.trainTrim, new.data = high.trainTrim, no.iterations = 500, bag.fnc = baggingTryCatch)

list.of.high.models <- high.model[[1]]
#predict on testing data
high.test.pred <- baggedPredictions(list.of.high.models, high.testTrim)

#test auc
high.test.pred[[1]]

#predictions for whole dataset
#add col to tell if in training vs testing 
high.model.prediction <- high.model[[2]] %>%
                          bind_rows(high.test.pred[[2]]) %>%
                          mutate(set=c(rep("train", dim(high.model[[2]])[1]), rep("test", dim(high.test.pred[[2]])[1])))

#save all the things
saveRDS(high.model, file="../data_out/MS_results/HighModel/model.rds")
saveRDS(high.test.pred, file="../data_out/MS_results/HighModel/testingPredictions.rds")
saveRDS(high.model.prediction, file="../data_out/MS_results/HighModel/wholePredictions.rds")


perf <- performance(p1,"tpr","fpr")
plot(perf,colorize=TRUE)
```


```{r two model Low}


#build model and predictions on training data
low.model <-  BaggedModel(form.x.y = glm.formula, training = low.trainTrim, new.data = low.trainTrim, no.iterations = 500, bag.fnc = baggingTryCatch)

list.of.low.models <- low.model[[1]]
#predict on testing data
low.test.pred <- baggedPredictions(list.of.low.models, low.testTrim)

#test auc
low.test.pred[[1]]

#predictions for whole dataset
#add col to tell if in training vs testing 
low.model.prediction <- low.model[[2]] %>%
                          bind_rows(low.test.pred[[2]]) %>%
                          mutate(set=c(rep("train", dim(low.model[[2]])[1]), rep("test", dim(low.test.pred[[2]])[1])))

#save all the things
saveRDS(low.model, file="../data_out/MS_results/LowModel/model.rds")
saveRDS(low.test.pred, file="../data_out/MS_results/LowModel/testingPredictions.rds")
saveRDS(low.model.prediction, file="../data_out/MS_results/LowModel/wholePredictions.rds")

```